### ISSUE TITLE
Split Payment (MercadoPago Connect)

### ISSUE THREAD

**Issue by rivervaladao** [mercadopago/code-examples#13]
Tenho o seguinte problema.
Estou usando a API para cobrar uma taxa de comissão por transação (Market Place), conforme descrito na documentação mercadopago-connect . Todos os fluxos anteriores são feitos, como por exemplo, criar uma aplicação, habilitar modo marketplace, se conectar com os meus usuários, obteer as credenciais dos meus usuários, porém no fluxo “Cobre uma comissão por transação” quando eu passo o parâmetro application_fee, estou obtendo o seguinte erro.

{"message":"You cannot use application_fee
with this payment.","error":"bad_request","status":400,"cause":[{"code":2059,"description":"You cannot use application_fee with this payment."}

Eu estou usando as credenciais do meu cliente. Vou explicar o fluxo que estou fazendo completo, pode ser que estou errando em algum fluxo:

1º Conecto os usuários e obtendo o authorization code, no código abaixo uso o APP_ID do meu usuário, obtido no aplication

https://auth.mercadopago.com.br/authorization?client_id=APP_ID&response_type=code&platform_id=mp&redirect_uri=http%3A%2F%2Fwww.URL_de_retorno.com

2º ) Obtendo o AUTHORIZATION_CODE,  eu uso para fazer obter as credenciais do meu usuário
usando o seguinte código:

curl -X POST \
     -H 'accept: application/json' \
     -H 'content-type: application/x-www-form-urlencoded' \
     'https://api.mercadopago.com/oauth/token' \
     -d 'client_secret=ACCESS_TOKEN' \  // Token de acesso do meu usuário.
     -d 'grant_type=authorization_code' \
     -d 'code=AUTHORIZATION_CODE' \     // aqui eu uso o AUTHORIZATION_CODE obtido no passo anterior.
     -d 'redirect_uri=REDIRECT_URI'

3º ) Com isso ele me retorna o seguinte :

{
    "access_token": "USER_AT",
    "public_key": "USER_PK",
    "refresh_token": "USER_RT",
    "live_mode": false,
    "user_id": 123456789,
    "token_type": "bearer",
    "expires_in": 15768000,
    "scope": "offline_access read write"
}

4º ) Até aqui tudo está funcionando conforme a documentação, porém no próximo passo, eu uso o que eu obtive no passo 3º que é o public_key, para gerar o token de acesso do meu usuário que é “Obtenha os dados do cartão do seu cliente” e “Obtenha o token de uso único para o cartão” linkhttps://www.mercadopago.com.br/developers/pt/solutions/payments/custom-checkout/charge-with-creditcard/javascript/. Para isso eu sigo os passos do checkout transparente onde eu faço um HTTP POST passando o public_key obtido no passo 3 e os dados do meu usuário, e assim obtendo o token.

5º ) A partir daí eu faço o fluxo de pagamento, cobrando uma comissão,

curl -X POST \
        -H 'accept: application/json' \
        -H 'content-type: application/json' \
        https://api.mercadopago.com/v1/payments?access_token=USER_AT \ // obtido no passo 3º
        -d '{
                "transaction_amount": 100,
                "token": "xxx", // Aqui eu passo o token obtido no passo 4º 
                "description": "Title of what you are paying for",
                "installments": 1,
                "payer": {
                        "email": "xxxx"
                },
                "payment_method_id": "visa",
                "application_fee": 2.56
        }'

E quando eu executo o código acima é que apresenta a mensagem.

Bom, é esse o fluxo que estou fazendo. Mais até o momento, não consegui prosseguir.

**Comment by rviera** [comment]
Olá @rivervaladao 

Você conseguiu implementar o split payment do mercadopago?

**Comment by rivervaladao** [comment]
Sim depois de muita tentativa e erro

**Comment by rviera** [comment]
Você sabe se o "Modo Produção" precisa estar ativado ou ele é válido apenas para o checkout transparente?

**Comment by rivervaladao** [comment]
Não coloquei em produção, só usei sand box, checkout transparente pela API https://api.mercadopago.com/v1/payments

**Comment by rviera** [comment]
Entendi. Obrigado. Poderia me ajudar com uma questão? No passo 2 (obter as credenciais do outro usuário) estou obtendo como resposta: "The client_id does not match the original". 

Eu passei os argumentos assim:

        $mp = new MP("TOKEN DO MARKETPLACE QUE IRÁ RECEBER A COMISSÃO");
                      
        $request = array(
        "uri" => "/oauth/token",
        "data" => array(
             "client_secret" => $mp->get_access_token(),
             "grant_type" => "authorization_code",
             "code" => "CÓDIGO DE VALIDAÇÃO DO OUTRO USUÁRIO",
             "redirect_uri" => "https://livreiroonline.com.br/oc-panel/profile/formaspagamento"
        ),
        "headers" => array(
            "content-type" => "application/x-www-form-urlencoded"
        ),
        "authenticate" => false
        );

        $mp->post($request);

**Comment by rviera** [comment]
Entendi. Obrigado. Poderia me ajudar com uma questão? No passo 2 (obter as credenciais do outro usuário) estou obtendo como resposta: "The client_id does not match the original".

Eu passei os argumentos assim:

    $mp = new MP("TOKEN DO MARKETPLACE QUE IRÁ RECEBER A COMISSÃO");
                  
    $request = array(
    "uri" => "/oauth/token",
    "data" => array(
         "client_secret" => $mp->get_access_token(),
         "grant_type" => "authorization_code",
         "code" => "CÓDIGO DE VALIDAÇÃO DO OUTRO USUÁRIO",
         "redirect_uri" => "URI"
    ),
    "headers" => array(
        "content-type" => "application/x-www-form-urlencoded"
    ),
    "authenticate" => false
    );

    $mp->post($request);

**Comment by rivervaladao** [comment]
o client_id é o APP ID do seu cliente (uma empresa que vende no seu marketplace -  precisa se registrar no mercado pago e te autorizar a fazer as transações por ele) me passa seu email que envio um roteiro que usei

**Comment by rviera** [comment]
Obrigado @rivervaladao: zaratustra@gmail.com

**Comment by albertobraschi** [comment]
@rivervaladao  há alguma maneiro digamos transparente para conseguir o **code** ou somente atraves dessa url: https://auth.mercadopago.com.br/authorization?client_id=APP_ID&response_type=code&platform_id=mp&redirect_uri=http%3A%2F%2Fwww.URL_de_retorno.com

e digamos que eu tenha 3 sellers no marketplace, precisarei executar isso para cada um deles?

obrigado desde já.

**Comment by rivervaladao** [comment]
@albertobraschi Não encontrei outra forma, infelizmente o pessoal do mercado pago não lê essas dúvidas aqui, nem no fórum, acho que eles nem existem !

**Comment by tganimi** [comment]
Olá @rivervaladao , tudo bem?

Estou tentando realizar a implementação do Split Payment também e estou com esse mesmo problema:

{"message":"You cannot use application_fee
with this payment.","error":"bad_request","status":400,"cause":[{"code":2059,"description":"You cannot use application_fee with this payment."}

Você disse acima que conseguiu finalizar a implementação. Qual foi a solução que você chegou para resolver o problema acima?

Poderia me auxiliar?

Obrigado desde já!

**Comment by sacjamm** [comment]
Olá @rivervaladao vc pode disponibilizar seu módulo completo?

**Comment by hugodeaguiar** [comment]
@rivervaladao Estou com o mesmo problema... Se puder compartilhar a solução conosco seria de grande ajuda! Obrigado.

**Comment by JorgeDanilo** [comment]
@tganimi 
No link [https://www.mercadopago.com.br/developers/pt/solutions/payments/custom-checkout/mercadopago-connect/](url)  passo **Crie sua aplicação** você certificou se  a opção que indica que irá operar com **MP Connect / Modo Marketplace** está marcada e  o scope está offline_access
Conforme imagem abaixo ?

<img src="https://uploaddeimagens.com.br/images/001/072/629/original/Sele%C3%A7%C3%A3o_001.png?1504364590" />

Se estiver marcada, provavelmente no fluxo abaixo, você deve estar passando o seu **APP_ID** e não o **APP_ID** do seu cliente. Certifique-se que realmente você está passando o APP_ID do seu cliente.

**_Se você estiver pedindo a autorização via browser tome o cuidado de você não estar autenticado com a sua própria conta. O authorization code poderá estar sendo o seu ao invés do seu cliente._**

Exemplo para obter o authorization code: 

1º Conecta os usuários e obter  o authorization code, no código abaixo uso o **APP_ID** do meu usuário, obtido no aplication

`https://auth.mercadopago.com.br/authorization?client_id=APP_ID&response_type=code&platform_id=mp&redirect_uri=SUA_URL_DE_RETORNO`

**Comment by hugodeaguiar** [comment]
@tganimi A causa deste erro pra mim, foi porque inverti os usuários de testes. Pra realizar os testes de compra, é necessário criar uma conta para representar o Seller, e outra para representar a conta que vai receber a comissão, certo? Verifique se estas contas não estão invertidas. 

Se o problema persistir aconselho entrar em contato através do email developers@mercadopago.com.br.

**Comment by tganimi** [comment]
@JorgeDanilo  e @hugodeaguiar  obrigado pelas respostas. Refazendo os fluxos, deu certo, estou conseguindo gerar os pagamentos via Sandbox, porém tenho outra dúvida: 

Os pagamentos que são feitos no ambiente Sandbox, não estão aparecendo no painel do mercado pago (tanto para o seller, tanto para a conta que recebe a comissão). Qual endpoint da API vocês utilizam para  puxar essas informações?

Obrigado.

**Comment by hugodeaguiar** [comment]
@tganimi Você esta usando usuários de  teste tanto como vendedor/filial/comprador?( https://www.mercadopago.com.br/developers/pt/related/test-users).

Seus pedidos podem estar vindo pra cá dependendo da forma que você está utilizando: mercadopago-sandbox.herokuapp.com

O endpoint é o padrão mesmo.

**Comment by tganimi** [comment]
Olá @hugodeaguiar ! Sim, estou utilizando os usuários de testes, para os três!

Quando acesso o endereço http://mercadopago-sandbox.herokuapp.com/collector/payments, autenticado com usuário que deveria receber a comissão, estou recebendo o seguinte erro:

TypeError: Cannot read property 'access_token' of null at Object.AppController.list [as handle] (/app/controllers/app.js:35:44) at next_layer (/app/node_modules/express/lib/router/route.js:103:13) at Object.LoginModel.isLogged [as handle] (/app/models/Login.js:9:17) at next_layer (/app/node_modules/express/lib/router/route.js:103:13) at Route.dispatch (/app/node_modules/express/lib/router/route.js:107:5) at /app/node_modules/express/lib/router/index.js:195:24 at param (/app/node_modules/express/lib/router/index.js:270:14) at param (/app/node_modules/express/lib/router/index.js:282:16) at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:298:3) at next (/app/node_modules/express/lib/router/index.js:189:19)

Vocês já tiveram esse erro?

**Comment by hugodeaguiar** [comment]
@tganimi É, também tive esse erro, na página de login, ao invés de utilizar o usuário, clique em "Autenticação com access_token de test".

Você está utilizando o access token e public key, que inicia com "TEST" ? Se sim, ele vai para o painel do heroku, o certo é usar as credenciais de produção mesmo, dos usuários de testes que você criou. Sim, é confuso, mas é o jeito que o mercado pago trata =/

**Comment by tganimi** [comment]
Olá @hugodeaguiar , realmente, precisei acessar pela opção "Autenticação com access_token de test". Acessando com o usuário tipo "Seller", consigo visualizar todos os meus pagamentos e nos objetos JSON, constam a taxa "application_fee" referente ao MP Connect, porém, quando acesso com o usuário que deveria receber a comissão, nada consta no painel. Isso está correto? Realmente não é para aparecer?

**Comment by hugodeaguiar** [comment]
@tganimi Então, esta foi uma dúvida que tive no começo também. O pessoal do Mercado pago informou que deveria ir para os dois painéis, mas eu não consegui fazer ir utilizando as credenciais de TEST e o heroku. 
Passei a utilizar as credenciais de produção dos usuários de teste, dai começou a ir para os dois painéis(sem ser o heroku, painel padrão do MP).

**Comment by tganimi** [comment]
@hugodeaguiar , então devo utilizar os tokens com início "APP_USR" dos usuários de testes?

Obrigado pela ajuda.

**Comment by hugodeaguiar** [comment]
@tganimi Isso, talvez de uma mensagem de erro informando que o usuário não está habilitado para usar em produção, o que aconteceu comigo, dai precisei entrar em contato com o pessoal do MP para eles liberarem o uso destes usuários.

Fico feliz em ajudar, no meu caso eu tive que aguardar vários dias para obter as respostas, já que a Doc do Mercado Pago não é clara.

**Comment by tganimi** [comment]
Sim @hugodeaguiar , a documentação não é clara e o suporte é muito demorado, mas vamos tentando.

Obrigado!

**Comment by tganimi** [comment]
@hugodeaguiar , a mensagem de erro que você recebeu ao tentar usar as credenciais de produção foi essa?

Array ( [message] => Unauthorized use of live credentials [error] => bad_request [status] => 400 [cause] => Array ( [code] => 5 [description] => Unauthorized use of live credentials [data] => ) ) 

Que tipo de liberação exatamente você solicitou à eles?

**Comment by hugodeaguiar** [comment]
@tganimi Esse mesmo.

Eu informei que estava ocorrendo este erro, e dai solicitaram os dados dos usuários de testes que eu estava utilizando. Alteraram algo lá  e pediram pra testar novamente.

**Comment by tganimi** [comment]
ok @hugodeaguiar , estou enviando um e-mail para eles.

obrigado.

**Comment by AleKoken** [comment]
Galera, uma dúvida. 
Existe a possibilidade de realizar a venda com mais de um vendedor na mesma transação utilizando o MP Connect?  ou para cada vendedor tem que ser feito um pagamento/checkout separado? (situação com mais de um vendedor no msm carrinho)
Se da para fazer tem algum exemplo de código?
Como vcs estão trabalhando?

**Comment by hugodeaguiar** [comment]
@AleKoken Você diz de pagar comissão pra mais de um vendedor?

**Comment by AleKoken** [comment]
@hugodeaguiar Tipo, vendedor A e vendedor B no msm carrinho, o cliente paga somente 1 vez e o marketplace recebe uma comissão de 15% de A e 15% de B - e cada vendedor recebe 85%.
É acho que seria pagar um comissão pra mais de um vendedor msm, só que no caso seria os 85% da venda. Tem como fazer isso?

**Comment by hugodeaguiar** [comment]
@AleKoken Entendi...

Não cheguei a trabalhar com este caso ainda... Mas pelo o que tem na doc, teoricamente seria só fazendo 2 pagamentos mesmo... O que seria meio complicado, porque o token do cartão de cŕedito só pode ser utilizado uma única vez.

Boa sorte! hehe

**Comment by AleKoken** [comment]
@hugodeaguiar Obrigado pela resposta, é provavelmente acho que não tem essa opção msm, se bem que o ML implementou o carrinho de compras agora, justamente com essa funcionalidade. 
Na doc do Moip tem bem detalhado essa opção de multipedido com 1 checkout apenas.

**Comment by russiann** [comment]
Bom dia galera, estou num projeto onde meus clientes iram cobrar de seus clientes pela minha plataforma (marketplace) mas aí tenho umas dúvidas em relação ao MercadoPago:
- É possível fazer split e pagamentos por **porcentavem** e **valor fixo**?
- É possível o **meu** cliente sequer saber da existencia do MercadoPage
- É possível o **meu** cliente solicitar a transferência de fundos para a sua conta bancária pela **minha** plataforma?

**Comment by hugodeaguiar** [comment]
@russiann Eae.

- É possível fazer split e pagamentos por porcentagem e valor fixo?
O Mercado Pago recebe valor fixo, você pode configurar porcentagem na sua plataforma, só que na hora de enviar você faz o calculo e envia o valor fixo.

- É possível o meu cliente sequer saber da existencia do MercadoPago.
Não, para trabalhar com comissão no Mercado Pago, ambas as partes precisam ter contas no Mercado Pago.

- É possível o meu cliente solicitar a transferência de fundos para a sua conta bancária pela minha plataforma?
No mercado Pago os valores caem na conta da filial assim que o pedido é capturado, desconheço algum controle que possa ter sobre isso.

**Comment by russiann** [comment]
@hugodeaguiar 

*Não, para trabalhar com comissão no Mercado Pago, ambas as partes precisam ter contas no Mercado Pago.*

Então o MercadoPago não provê uma funcionalidade de MarketPlace com transparência? tal como Iugu ou Pagar.me?

**Comment by hugodeaguiar** [comment]
@russiann Acredito que não cara.

Da uma olhada na Doc: https://www.mercadopago.com.br/developers/pt/solutions/payments/custom-checkout/mercadopago-connect/. 
É necessário criar uma url de autorização pra conta da filial permitir sua conta a fazer compra em nome dela...etc.

Se possuir essa opção com trasparência, eu realmente não tenho conhecimento...

**Comment by felipesalomao** [comment]
Pretendo vender ingressos. 
É possível  vender R$ 100,00. Taxa MP é de 5%. Dai desses 100, repassar 5 reais para MP (TAXA), 5 reais para mim (vendedor A) e 90 reais para organizador (vendedor B). Qualquer conta mercadopago está habilitado automaticamente para fazer split de pagamento, as taxas válidas para cobrança simples são as mesmas para marketplace. Hoje a taxa padrão deles é 4,99%. 

A api permite fazer checkout transparente, isso é, diretamente no meu carrinho do site ou app próprio ios e Android sem redirecionar para site deles? Permite também 1 click payment (salvar dados do cartão de crédito) para compras futuras.. A comunicação deles é muito fraca, é simplesmente impossível tirar esse tipo de dúvida no telefone/atendimento. Quanto não split payment as atendentes acham que estou xingando (tentei 6 vezes) rsrs.

**Comment by webfamilybr** [comment]
@rivervaladao @JorgeDanilo @hugodeaguiar 
ainda não consegui fazer isso funcionar.

minha é a seguinte:
aqui é isso mesmo ?
$mp = new MP("ACCESS_TOKEN DA MINHA CONTA QUE IRÁ RECEBER A COMISSÃO");

E esse trecho abaixo eu preciso executar ele sempre que for chamar o pagamento

$request = array(
"uri" => "/oauth/token",
"data" => array(
     "client_secret" => $mp->get_access_token(),
     "grant_type" => "authorization_code",
     "code" => "CÓDIGO DE VALIDAÇÃO DO USUÁRIO QUE VAI PAGAR A COMISSÃO",
     "redirect_uri" => "URI"
),
"headers" => array(
    "content-type" => "application/x-www-form-urlencoded"
),
"authenticate" => false
);

$mp->post($request);

Já inverti e desinvertir as contas e nada rsrs

obrigado.

**Comment by silascardoso** [comment]
@hugodeaguiar @russiann Infelizmente a API deles ainda não existe a figura de "fornecedores", apesar de existir a possibilidade de fazer split de pagamentos, essa possibilidade é restrita à usuários, ou seja, cada fornecedor tem que fazer um cadastro manualmente no MP, vincular sua conta bancária e ainda fazer a autorização para que aplicação envie comissões para ele, é muito burocrático.

**Comment by Raquel-Fernandes** [comment]
@rivervaladao você poderia enviar para o meu email o roteiro que você usou para o split? 
Desde já te agradeço

email: fernandessantos.r1@gmail.com

**Comment by albertoroque** [comment]
@rivervaladao Sei que o post é antigo, mas estou nesse mesmo passo da implementação e estou com o mesmo problema. Como você conseguiu realizar a implementação?  

Agradeço desde já

**Comment by elisandropsouza** [comment]
> @hugodeaguiar Tipo, vendedor A e vendedor B no msm carrinho, o cliente paga somente 1 vez e o marketplace recebe uma comissão de 15% de A e 15% de B - e cada vendedor recebe 85%.
> É acho que seria pagar um comissão pra mais de um vendedor msm, só que no caso seria os 85% da venda. Tem como fazer isso?

Boa noite,

Vc conseguiu fazer o pagamento para mais de um vendendor no mercadopago?

**Comment by hugodeaguiar** [comment]
> 
> 
> > @hugodeaguiar Tipo, vendedor A e vendedor B no msm carrinho, o cliente paga somente 1 vez e o marketplace recebe uma comissão de 15% de A e 15% de B - e cada vendedor recebe 85%.
> > É acho que seria pagar um comissão pra mais de um vendedor msm, só que no caso seria os 85% da venda. Tem como fazer isso?
> 
> Boa noite,
> 
> Vc conseguiu fazer o pagamento para mais de um vendendor no mercadopago?

Olá @elisandropsouza,

Não, somente para 1. 
Até o período que estavamos desenvolvendo, o MP ainda não tinha este cenário. Não sei dizer se já foi desenvolvido algo.
Abraço.

**Comment by elisandropsouza** [comment]
Boa tarde Hugo,

Mas valeu por ter dado um retorno.

Estou apanhando um pouco para desenvolver o pagamento.

Cada vez e uma surpresa nova, eu consegui fases o pagamento para um vendedor e pegar a comissão do marketplace, só q no painel consigo só ve o pagamento do vendedor do marketplace não aparece nada.

Mas valeu!

Elisandro Souza



Enviado do meu iPhone

Em 4 de mar de 2019, à(s) 13:37, Hugo Aguiar <notifications@github.com> escreveu:
